### ISSUE TITLE
Mobile Localization Issue

### ISSUE THREAD

**Issue by Zaf01** [magicleap/com.magicleap.spectator.networkanchors#8]
Hi,

I have followed the documentation of Mobile Localization to create a shared space between the Magic Leap One and an Android mobile device. I was able to build the scenes successfully and view them on the respective devices; I was able to detect the image target on both devices and a green cube prefab was spawned as mentioned in the documentation. However, when I press the bumper on the Magic Leap or the "Create anchor" button on the mobile device, all I get is a service status that states "Requesting Remote Anchor 101" but there is no anchor being created I assume? The cube in the center doesn't turn into a sphere to indicate successful localization on either device. I have tried to troubleshoot as per the documentation (ensured the magic leap recognizes the space before starting the application etc.) but still doesn't work. What could be the issue and how can I fix this?

**Comment by Babilinski** [comment]
Sorry to hear that you are having issues. To make sure I understand the issue, can you verify that you have shared world enabled on the Magic Leap? Also, do you localize into a space before launching the application?

**Comment by Zaf01** [comment]
Yes, I have the shared world enabled from the settings. On starting, the device recognizes the space and I launch the application normally after that. Pressing bumper/create anchor only shows a service status as "Requesting Remote Anchor 101" as mentioned previously, there is no indication of successful localization.

**Comment by Babilinski** [comment]
Can you provide the mldb log from the device  after the error occurs. You can run `mldb logcat > logcat.txt` after opening the command line using the Lab's sidebar shortcut
![image](https://user-images.githubusercontent.com/10122344/216779185-6cd58227-8319-403d-9b51-12534072a007.png)

**Comment by Babilinski** [comment]
You can also see if you see any errors using Device Bridge and filtering the Logs by the `Unity` tag.

**Comment by Zaf01** [comment]
Hi,

Here is the bug report.
 bugreport.zip.encrypted
<https://drive.google.com/file/d/1-LsrmD2K9EQfS6PhWMB_3oyCWyIaF05T/view?usp=drive_web>

**Comment by Babilinski** [comment]
Are you testing using the sample scene that was imported from this package? You can import it by opening the package manager, selecting the networkanchors package , then choosing the import option located in the package details.
